apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-container-2
  namespace: clamblob
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1000000Gi
  volumeName: pv-container-2
  storageClassName: azureblob-fuse-premium